version: '3'

tasks:
  build-win:
    desc: 构建项目
    platforms: [windows]
    cmds:
      - go build -o ./dist/windows/wwwzne.exe main.go
#      - cp ./wwwzne.config.json ./dist/windows

  run-win:
    desc: 运行项目
    cmds:
      - go run main.go
